# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a103280bf7d562a0d6ee45b091e033b2a476b65ec1d60926e8eb6b6a3b326382a1157778ca550fc04b04c153ddf167e594d7ff760651cb04ef054aafd8d9b935

test:
  secret_key_base: f3813a86bc2bdc4638c6ce226df911fab92ba241ebb5c70c7cf9e5c5a82a2d2b66c129a2544cfd31b91f747e552c9ef3b3482e8ca568735b76b867e36a2ff103

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
